spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mechanic_shop
    username: root
    password: mysql-25
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8080/token
          jwk-set-uri: http://localhost:8080/token

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    name: mechanic_shop.log